### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by ribagi** [CivClassic/CivDuties#1]
```
 Error occurred while enabling CivDuties v1.1.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/avaje/ebeaninternal/server/lib/sql/DataSourceException
        at vg.civcraft.mc.civduties.database.DatabaseManager.isValidConnection(DatabaseManager.java:39) ~[?:?]
        at vg.civcraft.mc.civduties.database.DatabaseManager.<init>(DatabaseManager.java:27) ~[?:?]
        at vg.civcraft.mc.civduties.CivDuties.onEnable(CivDuties.java:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-c3093ef-7e94e65]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.avaje.ebeaninternal.server.lib.sql.DataSourceException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-c3093ef-7e94e65]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]

```

**Comment by ribagi** [comment]
@TealNerd

**Comment by ribagi** [comment]
Fixed via https://github.com/CivClassic/CivDuties/pull/2
